[db]

url = ""
user = "root"
password = "123456"
name = "tss"

[api]

addr = ":9000"

[eth]

enable = true
tss_client_address = "0x5a15c9f265006bfc1c82fa534067e1231c4127d1"
url = "http://localhost:9545"

[tele]
enable = false
url = ""

## the simulation config only works when the service is runing on simulation mode
[simulation]
pool_pub_key = ""
party_pub_keys = ""